title : "Example website"
theme : "hugo-PaperMod"


menu:
  main:
    - identifier: Page1
      name: Page1
      url: /page1/index.html
    - identifier: Page2
      name: Page2
      url: /page2/index.html
